# Generated by Django 3.0.5 on 2025-09-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_auto_20250908_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctor',
        ),
        migrations.AddField(
            model_name='patient',
            name='assignedDoctorId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
